baseURL = "https://freeos.me/wiki/"
languageCode = "en-us"
title = "FreeOS.me Wiki"
defaultContentLanguage = "en"
enableRobotsTXT = true
theme = "hextra"

[params]
  description = "FreeOS.me documentation and knowledge base"
  author = "Vicente García Díaz"

[markup]
  [markup.highlight]
    noClasses = false

[[menu.main]]
  name = "Blog"
  url = "https://freeos.me/blog/"
  weight = 10

[[menu.main]]
  name = "Community"
  url = "https://freeos.me/community.html"
  weight = 20

[[menu.main]]
  name = "GitLab"
  url = "https://gitlab.com/freeos.me"
  weight = 30
