baseURL = "https://freeos.me/blog/"
languageCode = "en-us"
title = "FreeOS.me Blog"
defaultContentLanguage = "en"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "Updates, notes, and development logs for FreeOS.me"
  author = "Vicente García Díaz"
  useGlobalShell = false
